### ISSUE TITLE
Django 教材で未着手の内容リストアップ

### ISSUE THREAD

**Issue by technicakidz** [geek-mama/samurai_HTML-CSS2#10]
### 概要
教材で取り組むべき実装内容が残っていないか相談して決める

### 完了条件
- [ ] この issue コメントで未着手の実装がリストアップされている
- [ ] リストアップした内容について相談のもと着手すべきか確認されている

**Comment by geek-mama** [comment]
こちらはどのように進めていくとよろしいでしょうか？

**Comment by technicakidz** [comment]
コツツボ本は全て網羅していたのでしたっけ？自分の認識では少しやり残しがあると記憶してましたので、その項目を列挙するイメージでしたがいかがでしょうか。 @geek-mama

**Comment by geek-mama** [comment]
はい、2つのアプリを作成する内容でして、2つとも作成し終えました。

**Comment by technicakidz** [comment]
技術書は完遂されていたのですね、失礼しました。それではこちらのissueは closeください。
