### ISSUE TITLE
Django アプリの構成を解説する

### ISSUE THREAD

**Issue by technicakidz** [geek-mama/samurai_HTML-CSS2#8]
**概要**
開発している/していた Django アプリについて理解を深めるため、資料などをもとに解説する

**完了条件**
- [x] 資料等が作成されている
- [x] 自身の言葉で解説する
- [x] 発表後の質問に回答し、不明点がこのissueコメントに明記されている
- [x] レビュアー(講師)へ解説内容を発表する

**Comment by geek-mama** [comment]
理解が乏しく申し訳ありません。
現在開発しているDjangoアプリとは、どのアプリを指しますでしょうか？
教材を基に写経したアプリを、いくつかここにもあげていますが、開発中のものはありません。

**Comment by technicakidz** [comment]
現在手元で動かすことのできるアプリケーションを選んでいただければと思います。
その際に構成の説明を行いやすいシンプルなものがあれば理想です。

**Comment by geek-mama** [comment]
承知しました。ご説明いただきありがとうございました。

要件に適っているか不安ですが、資料を作成しました。
[「reviewproject」について](https://docs.google.com/spreadsheets/d/1PxIeNKYILd_7IE9NpV2DFqE5Hr7YWIX3Po9-rFyIaoY/edit?usp=sharing)

ご確認、よろしくお願い致します。

**Comment by technicakidz** [comment]
追加として，Django のアプリモデルを説明する資料を作成してみましょう．たとえば以下のようなイメージです．
https://gihyo.jp/dev/serial/01/start_webap/0003

Django がMVCモデルなのか，も合わせて調べてみましょう．

**Comment by geek-mama** [comment]
MTVモデルについて、追記しました。

**Comment by technicakidz** [comment]
確認しました、次回に発表いただきますので図など作成すると解説がしやすいと思いました。質問タイムを含めず3分程度を想定していますがいかがでしょうか。

**Comment by geek-mama** [comment]
簡単なものですが、図を追記しました。

**Comment by technicakidz** [comment]
@geek-mama  こちらが参考になると思います。
このモデルにのっとると今回開発したアプリ（どちらでも構いませんが）はどこのファイルがどのようにあてはまるかを考えて修正してみましょう！
https://djangobrothers.com/tutorials/memo_app/mtv/

**Comment by geek-mama** [comment]
@technicakidz 

追記しました。

**Comment by technicakidz** [comment]
スプレッドシートで文字が見切れるなどしているようです。発表までに体裁整えるために google スライドアプリで作成するとよさそうです。

**Comment by geek-mama** [comment]
@technicakidz 

[「reviewproject」の概要](https://docs.google.com/presentation/d/1DwYOAs9XAaWt9dgPzs2KVnKbQVMCpsrKxdMOowZSHIs/edit?usp=sharing)

スライドに変更しました。

**Comment by geek-mama** [comment]
各ページにテーマを持たせ、最初に目次にする

**Comment by geek-mama** [comment]
仕様についての問題点を記載する
