### ISSUE TITLE
githubユーザ付けの projects を作成する

### ISSUE THREAD

**Issue by technicakidz** [geek-mama/samurai_HTML-CSS2#9]
### 概要
プロジェクトごとでなく，全体の課題やタスク管理をするための projects を作成する．

### 問題点
現在プロジェクトごとの issue でのみ課題等を積んでいくことになっている．
このプロジェクト(samurai_HTML-CSS2)以外の課題のときどのプロジェクト対象のものかわかりにくい.

### 完了条件

- [x] 適切な名前の projects がユーザ画面から作成されている
- [x] タスクの進行状況がわかる状態(Backlog, In Progress, Doneなど)になっている
- [x] レビュワーに共有されている

**Comment by geek-mama** [comment]
新しいリポジトリを作成するということでしょうか？

**Comment by technicakidz** [comment]
この画面にある projects です．
![スクリーンショット 0003-04-18 14 38 50](https://user-images.githubusercontent.com/6193750/115135495-dd45c900-a053-11eb-881c-094e1f19e6c2.png)

**Comment by geek-mama** [comment]
大変申し訳ありません。
未だ、理解できずにおります。

**Comment by technicakidz** [comment]
理解できていないところはどのあたりでしょうか？この画面にいきつくところ、projects の作成方法など不明点を明らかにしてもらうと助かります。 @geek-mama

**Comment by geek-mama** [comment]
projects の作成方法がわかりません。

**Comment by geek-mama** [comment]
@technicakidz 

>この画面にある projects

という点が理解できていませんでした。申し訳ありません。
プロジェクトを作成しました。

**Comment by technicakidz** [comment]
@geek-mama 
それでは以下を参照のもと、私(@technicakidz)をコラボレータとして追加いただきたいです。
現在、作成いただいた projects を追加したりすることができないためです。
https://docs.github.com/ja/github/setting-up-and-managing-your-github-user-account/managing-access-to-your-user-accounts-project-boards
不明点あればご質問ください！

**Comment by geek-mama** [comment]
@technicakidz 

コラボレータの追加、できておりますでしょうか？

**Comment by technicakidz** [comment]
@geek-mama 確認しましたが特に権限追加できていなさそうでした 😢 （privateでみえてはいるので付与いただいた権限が半分くらいなのかもしれません）

**Comment by geek-mama** [comment]
@technicakidz 

失礼しました！
権限が「Read」になっていました。
「Admin」に変更しました。

**Comment by technicakidz** [comment]
@geek-mama 確認できました（課題 issue カードも追加しました）ので close でokです！
